### ISSUE TITLE
Sardi-Flat-Numix: wrong icon for telegram

### ISSUE THREAD

**Issue by TheCrazyRabbit13** [erikdubois/Sardi-Flat-Mixing#1]
Since the last update two days ago the icon of Sardi-Flat-Numix for Telegram shows the same icon like that on the panel everywhere. I tried by myself to get the nice round and flat icon back but it didn't work. Maybe you can do something about this on the developer side.

Greetings

**Comment by erikdubois** [comment]
https://github.com/erikdubois/Sardi/issues/275
